'use strict'
/* eslint quote-props: "off" */module.exports = {
  '00': {
    categoryId: '00',
    categoryName: 'Generalized Controllers',
    examplesOfDevices: 'ControLinc, RemoteLinc, SignaLinc, etc.',
    subcategories: {
      '04': {
        categoryId: '00',
        subcategoryId: '04',
        productKey: '000000',
        deviceDescription: 'ControLinc',
        modelNumber: '2430',
      },
      '05': {
        categoryId: '00',
        subcategoryId: '05',
        productKey: '000034',
        deviceDescription: 'RemoteLinc',
        modelNumber: '2440',
      },
      '06': {
        categoryId: '00',
        subcategoryId: '06',
        productKey: '000000',
        deviceDescription: 'ICON Tabletop Controller',
        modelNumber: '2830',
      },
      '08': {
        categoryId: '00',
        subcategoryId: '08',
        productKey: '00003D',
        deviceDescription: 'EZBridge/EZServer',
      },
      '09': {
        categoryId: '00',
        subcategoryId: '09',
        productKey: '000000',
        deviceDescription: 'SignaLinc RF Signal Enhancer',
        modelNumber: '2442',
      },
      '0A': {
        categoryId: '00',
        subcategoryId: '0A',
        productKey: '000007',
        deviceDescription: 'Poolux LCD Controller',
      },
      '0B': {
        categoryId: '00',
        subcategoryId: '0B',
        productKey: '000022',
        deviceDescription: 'Access Point (Wireless Phase Coupler)',
        modelNumber: '2443',
      },
      '0C': {
        categoryId: '00',
        subcategoryId: '0C',
        productKey: '000028',
        deviceDescription: 'IES Color Touchscreen',
        modelNumber: '12005',
      },
      '0D': {
        categoryId: '00',
        subcategoryId: '0D',
        productKey: '00004D',
        deviceDescription: 'SmartLabs KeyFOB',
        modelNumber: '',
      },
      '0E': {
        categoryId: '00',
        subcategoryId: '0E',
        deviceDescription: 'RemoteLinc EZ',
        modelNumber: '2440EZ',
      },
      '10': {
        categoryId: '00',
        subcategoryId: '10',
        productKey: '000000',
        deviceDescription: 'RemoteLinc 2 Keypad, 4 Scene',
        modelNumber: '2444A2WH4',
      },
      '11': {
        categoryId: '00',
        subcategoryId: '11',
        productKey: '000000',
        deviceDescription: 'RemoteLinc 2 Switch',
        modelNumber: '2444A3',
      },
      '12': {
        categoryId: '00',
        subcategoryId: '12',
        productKey: '000000',
        deviceDescription: 'RemoteLinc 2 Keypad, 8 Scene',
        modelNumber: '2444A2WH8',
      },
      '13': {
        categoryId: '00',
        subcategoryId: '13',
        deviceDescription: 'Insteon Diagnostics Keypad',
        modelNumber: '2993-222',
      },
      '14': {
        categoryId: '00',
        subcategoryId: '14',
        productKey: '000000',
        deviceDescription: 'Insteon Mini Remote - 4 Scene (869 MHz)',
        modelNumber: '2342-432',
      },
      '15': {
        categoryId: '00',
        subcategoryId: '15',
        productKey: '000000',
        deviceDescription: 'Insteon Mini Remote - Switch (869 MHz)',
        modelNumber: '2342-442',
      },
      '16': {
        categoryId: '00',
        subcategoryId: '16',
        productKey: '000000',
        deviceDescription: 'Insteon Mini Remote - 8 Scene (869 MHz)',
        modelNumber: '2342-422',
      },
      '17': {
        categoryId: '00',
        subcategoryId: '17',
        productKey: '000000',
        deviceDescription: 'Insteon Mini Remote - 4 Scene (921 MHz)',
        modelNumber: '2342-532',
      },
      '18': {
        categoryId: '00',
        subcategoryId: '18',
        productKey: '000000',
        deviceDescription: 'Insteon Mini Remote - 8 Scene (921 MHz)',
        modelNumber: '2342-522',
      },
      '19': {
        categoryId: '00',
        subcategoryId: '19',
        productKey: '000000',
        deviceDescription: 'Insteon Mini Remote - Switch (921 MHz)',
        modelNumber: '2342-542',
      },
      '1A': {
        categoryId: '00',
        subcategoryId: '1A',
        productKey: '000000',
        deviceDescription: 'Insteon Mini Remote - 8 Scene (915 MHz)',
        modelNumber: '2342-222',
      },
      '1B': {
        categoryId: '00',
        subcategoryId: '1B',
        productKey: '000000',
        deviceDescription: 'Insteon Mini Remote - 4 Scene (915 MHz)',
        modelNumber: '2342-232',
      },
      '1C': {
        categoryId: '00',
        subcategoryId: '1C',
        productKey: '000000',
        deviceDescription: 'Insteon Mini Remote - Switch (915 MHz)',
        modelNumber: '2342-242',
      },
      '1D': {
        categoryId: '00',
        subcategoryId: '1D',
        productKey: '000022',
        deviceDescription: 'Range Extender',
        modelNumber: '2992-222',
      },
    },
  },
  '01': {
    categoryId: '01',
    categoryName: 'Dimmable Lighting Control',
    examplesOfDevices: 'Dimmable Light Switches, Dimmable Plug-In Modules',
    subcategories: {
      '00': {
        categoryId: '01',
        subcategoryId: '00',
        productKey: '000000',
        deviceDescription: 'LampLinc 3-Pin',
        modelNumber: '2456D3',
      },
      '01': {
        categoryId: '01',
        subcategoryId: '01',
        productKey: '000000',
        deviceDescription: 'SwitchLinc Dimmer',
        modelNumber: '2476D',
      },
      '02': {
        categoryId: '01',
        subcategoryId: '02',
        productKey: '000000',
        deviceDescription: 'In-LineLinc Dimmer',
        modelNumber: '2475D',
      },
      '03': {
        categoryId: '01',
        subcategoryId: '03',
        productKey: '000000',
        deviceDescription: 'ICON Dimmer Switch',
        modelNumber: '2876DB',
      },
      '04': {
        categoryId: '01',
        subcategoryId: '04',
        productKey: '000000',
        deviceDescription: 'SwitchLinc Dimmer (High Wattage)',
        modelNumber: '2476DH',
      },
      '05': {
        categoryId: '01',
        subcategoryId: '05',
        productKey: '000041',
        deviceDescription: 'Keypad Countdown Timer with Dimmer',
        modelNumber: '2484DWH8',
      },
      '06': {
        categoryId: '01',
        subcategoryId: '06',
        productKey: '000000',
        deviceDescription: 'LampLinc Dimmer (2-Pin)',
        modelNumber: '2456D2',
      },
      '07': {
        categoryId: '01',
        subcategoryId: '07',
        productKey: '000000',
        deviceDescription: 'ICON LampLinc',
        modelNumber: '2856D2B',
      },
      '08': {
        categoryId: '01',
        subcategoryId: '08',
        productKey: '000040',
        deviceDescription: 'SwitchLinc Dimmer Countdown Timer',
        modelNumber: '2476DT',
      },
      '09': {
        categoryId: '01',
        subcategoryId: '09',
        productKey: '000037',
        deviceDescription: 'KeypadLinc Dimmer',
        modelNumber: '2486D',
      },
      '0A': {
        categoryId: '01',
        subcategoryId: '0A',
        productKey: '000000',
        deviceDescription: 'Icon In-Wall Controller',
        modelNumber: '2886D',
      },
      '0B': {
        categoryId: '01',
        subcategoryId: '0B',
        productKey: '00001C',
        deviceDescription: 'Insteon Dimmer Module, France (869 MHz)',
        modelNumber: '2632-422',
      },
      '0C': {
        categoryId: '01',
        subcategoryId: '0C',
        productKey: '00001D',
        deviceDescription: 'KeypadLinc Dimmer',
        modelNumber: '2486DWH8',
      },
      '0D': {
        categoryId: '01',
        subcategoryId: '0D',
        productKey: '00001E',
        deviceDescription: 'SocketLinc',
        modelNumber: '2454D',
      },
      '0E': {
        categoryId: '01',
        subcategoryId: '0E',
        productKey: '00004B',
        deviceDescription: 'LampLinc (Dual-Band)',
        modelNumber: '2457D2',
      },
      '0F': {
        categoryId: '01',
        subcategoryId: '0F',
        productKey: '000000',
        deviceDescription: 'Insteon Dimmer Module, Germany (869 MHz)',
        modelNumber: '2632-432',
      },
      '11': {
        categoryId: '01',
        subcategoryId: '11',
        productKey: '000000',
        deviceDescription: 'Insteon Dimmer Module, UK (869 MHz)',
        modelNumber: '2632-442',
      },
      '12': {
        categoryId: '01',
        subcategoryId: '12',
        productKey: '000000',
        deviceDescription: 'Insteon Dimmer Module, Aus/NZ (921 MHz)',
        modelNumber: '2632-522',
      },
      '13': {
        categoryId: '01',
        subcategoryId: '13',
        productKey: '000032',
        deviceDescription: 'ICON SwitchLinc Dimmer Lixar/Bell Canada',
        modelNumber: '2676D-B',
      },
      '17': {
        categoryId: '01',
        subcategoryId: '17',
        productKey: '000000',
        deviceDescription: 'ToggleLinc Dimmer',
        modelNumber: '2466D',
      },
      '18': {
        categoryId: '01',
        subcategoryId: '18',
        productKey: '00003F',
        deviceDescription: 'Icon SwitchLinc Dimmer Inline Companion',
        modelNumber: '2474D',
      },
      '19': {
        categoryId: '01',
        subcategoryId: '19',
        productKey: '00004E',
        deviceDescription: 'SwitchLinc Dimmer [with beeper]',
        modelNumber: '2476D',
      },
      '1A': {
        categoryId: '01',
        subcategoryId: '1A',
        productKey: '00004F',
        deviceDescription: 'In-LineLinc Dimmer [with beeper]',
        modelNumber: '2475D',
      },
      '1B': {
        categoryId: '01',
        subcategoryId: '1B',
        productKey: '00001D',
        deviceDescription: 'KeypadLinc Dimmer',
        modelNumber: '2486DWH6',
      },
      '1C': {
        categoryId: '01',
        subcategoryId: '1C',
        productKey: '000051',
        deviceDescription: 'KeypadLinc Dimmer',
        modelNumber: '2486DWH8',
      },
      '1D': {
        categoryId: '01',
        subcategoryId: '1D',
        productKey: '000052',
        deviceDescription: 'SwitchLinc Dimmer (High Wattage) [with beeper]',
        modelNumber: '2476DH',
      },
      '1E': {
        categoryId: '01',
        subcategoryId: '1E',
        productKey: '000000',
        deviceDescription: 'ICON Switch Dimmer',
        modelNumber: '2876DB',
      },
      '1F': {
        categoryId: '01',
        subcategoryId: '1F',
        productKey: '000000',
        deviceDescription: 'ToggleLinc Dimmer [with beeper]',
        modelNumber: '2466DW',
      },
      '20': {
        categoryId: '01',
        subcategoryId: '20',
        productKey: '000000',
        deviceDescription: 'SwitchLinc Dimmer (Dual-Band)',
        modelNumber: '2477D',
      },
      '21': {
        categoryId: '01',
        subcategoryId: '21',
        productKey: '000000',
        deviceDescription: 'OutletLinc Dimmer (Dual-Band)',
        modelNumber: '2472D',
      },
      '22': {
        categoryId: '01',
        subcategoryId: '22',
        productKey: '000000',
        deviceDescription: 'LampLinc',
        modelNumber: '2457D2X',
      },
      '23': {
        categoryId: '01',
        subcategoryId: '23',
        deviceDescription: 'LampLinc Dual-Band EZ',
        modelNumber: '2457D2EZ',
      },
      '24': {
        categoryId: '01',
        subcategoryId: '24',
        productKey: '000000',
        deviceDescription: 'SwitchLinc 2-Wire Dimmer (RF)',
        modelNumber: '2474DWH',
      },
      '25': {
        categoryId: '01',
        subcategoryId: '25',
        productKey: '000000',
        deviceDescription: 'In-LineLinc 0-10VDC Dimmer/Dual-SwitchDB',
        modelNumber: '2475DA2',
      },
      '27': {
        categoryId: '01',
        subcategoryId: '27',
        productKey: '000087',
        deviceDescription: 'Wall Dimmer',
        modelNumber: '4701',
      },
      '29': {
        categoryId: '01',
        subcategoryId: '29',
        productKey: '000089',
        deviceDescription: 'Wall Keypad Dimmer',
        modelNumber: '4703',
      },
      '2A': {
        categoryId: '01',
        subcategoryId: '2A',
        productKey: '00008B',
        deviceDescription: 'Plug-in Dimmer',
        modelNumber: '4705',
      },
      '2B': {
        categoryId: '01',
        subcategoryId: '2B',
        productKey: '000091',
        deviceDescription: 'Wall Dimmer - 1000W',
        modelNumber: '4711',
      },
      '2C': {
        categoryId: '01',
        subcategoryId: '2C',
        productKey: '000092',
        deviceDescription: 'In-Line Dimmer',
        modelNumber: '4712',
      },
      '2D': {
        categoryId: '01',
        subcategoryId: '2D',
        productKey: '00009E',
        deviceDescription: 'SwitchLinc-Dimmer Dual-Band 1000W',
        modelNumber: '2477DH',
      },
      '2E': {
        categoryId: '01',
        subcategoryId: '2E',
        productKey: '000000',
        deviceDescription: 'FanLinc',
        modelNumber: '2475F',
      },
      '2F': {
        categoryId: '01',
        subcategoryId: '2F',
        productKey: '000000',
        deviceDescription: 'KeypadLinc Schedule Timer with Dimmer',
        modelNumber: '2484DST6',
      },
      '30': {
        categoryId: '01',
        subcategoryId: '30',
        productKey: '000000',
        deviceDescription: 'SwitchLinc Dimmer',
        modelNumber: '2476D',
      },
      '31': {
        categoryId: '01',
        subcategoryId: '31',
        productKey: '000000',
        deviceDescription: 'SwitchLinc Dimmer 240V-50/60Hz Dual-Band',
        modelNumber: '2478D',
      },
      '32': {
        categoryId: '01',
        subcategoryId: '32',
        productKey: '000000',
        deviceDescription: 'In-LineLinc Dimmer (Dual Band)',
        modelNumber: '2475DA1',
      },
      '34': {
        categoryId: '01',
        subcategoryId: '34',
        productKey: '000000',
        deviceDescription: 'Insteon DIN Rail Dimmer (915 MHz)',
        modelNumber: '2452-222',
      },
      '35': {
        categoryId: '01',
        subcategoryId: '35',
        productKey: '000000',
        deviceDescription: 'Insteon Micro Dimmer (915 MHz)',
        modelNumber: '2442-222',
      },
      '36': {
        categoryId: '01',
        subcategoryId: '36',
        productKey: '000000',
        deviceDescription: 'Insteon DIN Rail Dimmer (869 MHz)',
        modelNumber: '2452-422',
      },
      '37': {
        categoryId: '01',
        subcategoryId: '37',
        productKey: '000000',
        deviceDescription: 'Insteon DIN Rail Dimmer (921 MHz)',
        modelNumber: '2452-522',
      },
      '38': {
        categoryId: '01',
        subcategoryId: '38',
        productKey: '000000',
        deviceDescription: 'Insteon Micro Dimmer (869 MHz)',
        modelNumber: '2442-422',
      },
      '39': {
        categoryId: '01',
        subcategoryId: '39',
        productKey: '000000',
        deviceDescription: 'Insteon Micro Dimmer (921 MHz)',
        modelNumber: '2442-522',
      },
      '3A': {
        categoryId: '01',
        subcategoryId: '3A',
        productKey: '000000',
        deviceDescription: 'LED Bulb 240V (915 MHz) - Screw-in Base',
        modelNumber: '2672-222',
      },
      '3B': {
        categoryId: '01',
        subcategoryId: '3B',
        productKey: '000000',
        deviceDescription: 'LED Bulb 240V Europe - Screw-in Base',
        modelNumber: '2672-422',
      },
      '3C': {
        categoryId: '01',
        subcategoryId: '3C',
        productKey: '000000',
        deviceDescription: 'LED Bulb 240V Aus/NZ - Screw-in Base',
        modelNumber: '2672-522',
      },
      '3D': {
        categoryId: '01',
        subcategoryId: '3D',
        productKey: '000000',
        deviceDescription: 'Insteon Ballast Dimmer (869 MHz)',
        modelNumber: '2446-422',
      },
      '3E': {
        categoryId: '01',
        subcategoryId: '3E',
        productKey: '000000',
        deviceDescription: 'Insteon Ballast Dimmer (921 MHz)',
        modelNumber: '2446-522',
      },
      '3F': {
        categoryId: '01',
        subcategoryId: '3F',
        productKey: '000000',
        deviceDescription: 'Insteon Fixture Dimmer (869 MHz)',
        modelNumber: '2447-422',
      },
      '40': {
        categoryId: '01',
        subcategoryId: '40',
        productKey: '000000',
        deviceDescription: 'Insteon Fixture Dimmer (921 MHz)',
        modelNumber: '2447-522',
      },
      '41': {
        categoryId: '01',
        subcategoryId: '41',
        productKey: '000000',
        deviceDescription: 'Keypad Dimmer Dual-Band, 8 Button',
        modelNumber: '2334-222',
      },
      '42': {
        categoryId: '01',
        subcategoryId: '42',
        productKey: '000000',
        deviceDescription: 'Keypad Dimmer Dual-Band, 6 Button',
        modelNumber: '2334-232',
      },
      '49': {
        categoryId: '01',
        subcategoryId: '49',
        productKey: '000000',
        deviceDescription: 'LED Bulb PAR38 US/Can - Screw-in Base',
        modelNumber: '2674-222',
      },
      '4A': {
        categoryId: '01',
        subcategoryId: '4A',
        productKey: '000000',
        deviceDescription: 'LED Bulb PAR38 Europe - Screw-in Base',
        modelNumber: '2674-422',
      },
      '4B': {
        categoryId: '01',
        subcategoryId: '4B',
        productKey: '000000',
        deviceDescription: 'LED Bulb PAR38 Aus/NZ - Screw-in Base',
        modelNumber: '2674-522',
      },
      '4C': {
        categoryId: '01',
        subcategoryId: '4C',
        productKey: '000000',
        deviceDescription: 'LED Bulb 240V Europe - Bayonet Base',
        modelNumber: '2672-432',
      },
      '4D': {
        categoryId: '01',
        subcategoryId: '4D',
        productKey: '000000',
        deviceDescription: 'LED Bulb 240V Aus/NZ - Bayonet Base',
        modelNumber: '2672-532',
      },
      '4E': {
        categoryId: '01',
        subcategoryId: '4E',
        productKey: '000000',
        deviceDescription: 'LED Bulb PAR38 Europe - Bayonet Base',
        modelNumber: '2674-432',
      },
      '4F': {
        categoryId: '01',
        subcategoryId: '4F',
        productKey: '000000',
        deviceDescription: 'LED Bulb PAR38 Aus/NZ - Bayonet Base',
        modelNumber: '2674-532',
      },
      '50': {
        categoryId: '01',
        subcategoryId: '50',
        deviceDescription: 'Insteon Dimmer Module, Chile (915 MHz)',
        modelNumber: '2632-452',
      },
      '51': {
        categoryId: '01',
        subcategoryId: '51',
        deviceDescription: 'LED Bulb 240V (915 MHz) - Screw-in Base',
        modelNumber: '2672-452',
      },
    },
  },
  '02': {
    categoryId: '02',
    categoryName: 'Switched Lighting Control',
    examplesOfDevices: 'Relay Switches, Relay Plug-In Modules',
    subcategories: {
      '05': {
        categoryId: '02',
        subcategoryId: '05',
        productKey: '000042',
        deviceDescription: 'KeypadLinc 8-button On/Off Switch',
        modelNumber: '2486SWH8',
      },
      '06': {
        categoryId: '02',
        subcategoryId: '06',
        productKey: '000048',
        deviceDescription: 'Outdoor ApplianceLinc',
        modelNumber: '2456S3E',
      },
      '07': {
        categoryId: '02',
        subcategoryId: '07',
        productKey: '000029',
        deviceDescription: 'TimerLinc',
        modelNumber: '2456S3T',
      },
      '08': {
        categoryId: '02',
        subcategoryId: '08',
        productKey: '000023',
        deviceDescription: 'OutletLinc',
        modelNumber: '2473S',
      },
      '09': {
        categoryId: '02',
        subcategoryId: '09',
        productKey: '000000',
        deviceDescription: 'ApplianceLinc (3-Pin)',
        modelNumber: '2456S3',
      },
      '0A': {
        categoryId: '02',
        subcategoryId: '0A',
        productKey: '000000',
        deviceDescription: 'SwitchLinc Relay',
        modelNumber: '2476S',
      },
      '0B': {
        categoryId: '02',
        subcategoryId: '0B',
        productKey: '000000',
        deviceDescription: 'ICON On/Off Switch',
        modelNumber: '2876S',
      },
      '0C': {
        categoryId: '02',
        subcategoryId: '0C',
        productKey: '000000',
        deviceDescription: 'Icon Appliance Module',
        modelNumber: '2856S3',
      },
      '0D': {
        categoryId: '02',
        subcategoryId: '0D',
        productKey: '000000',
        deviceDescription: 'ToggleLinc Relay',
        modelNumber: '2466S',
      },
      '0E': {
        categoryId: '02',
        subcategoryId: '0E',
        productKey: '000000',
        deviceDescription: 'SwitchLinc Relay Countdown Timer',
        modelNumber: '2476ST',
      },
      '0F': {
        categoryId: '02',
        subcategoryId: '0F',
        productKey: '000036',
        deviceDescription: 'KeypadLinc On/Off',
        modelNumber: '2486SWH6',
      },
      '10': {
        categoryId: '02',
        subcategoryId: '10',
        productKey: '00001B',
        deviceDescription: 'In-LineLinc Relay',
        modelNumber: '2475S',
      },
      '11': {
        categoryId: '02',
        subcategoryId: '11',
        productKey: '00003C',
        deviceDescription: 'EZSwitch30 (240V, 30A load controller)',
      },
      '12': {
        categoryId: '02',
        subcategoryId: '12',
        productKey: '00003E',
        deviceDescription: 'ICON In-lineLinc Relay Companion',
        modelNumber: '2474 S/D',
      },
      '13': {
        categoryId: '02',
        subcategoryId: '13',
        productKey: '000033',
        deviceDescription: 'ICON SwitchLinc Relay Lixar/Bell Canada',
        modelNumber: '2676R-B',
      },
      '14': {
        categoryId: '02',
        subcategoryId: '14',
        productKey: '000045',
        deviceDescription: 'In-LineLinc Relay with Sense',
        modelNumber: '2475S2',
      },
      '15': {
        categoryId: '02',
        subcategoryId: '15',
        productKey: '000047',
        deviceDescription: 'SwitchLinc Relay with Sense',
        modelNumber: '2476SS',
      },
      '16': {
        categoryId: '02',
        subcategoryId: '16',
        productKey: '000000',
        deviceDescription: 'ICON On/Off Switch (25 max links)',
        modelNumber: '2876S',
      },
      '17': {
        categoryId: '02',
        subcategoryId: '17',
        productKey: '000000',
        deviceDescription: 'ICON Appliance Module',
        modelNumber: '2856S3B',
      },
      '18': {
        categoryId: '02',
        subcategoryId: '18',
        productKey: '000060',
        deviceDescription: 'SwitchLinc 220V Relay',
        modelNumber: '2494S220',
      },
      '19': {
        categoryId: '02',
        subcategoryId: '19',
        productKey: '000000',
        deviceDescription: 'SwitchLinc 220V Relay [with beeper]',
        modelNumber: '2494S220',
      },
      '1A': {
        categoryId: '02',
        subcategoryId: '1A',
        productKey: '000000',
        deviceDescription: 'ToggleLinc Relay [with Beeper]',
        modelNumber: '2466SW',
      },
      '1C': {
        categoryId: '02',
        subcategoryId: '1C',
        productKey: '000000',
        deviceDescription: 'SwitchLinc Relay',
        modelNumber: '2476S',
      },
      '1D': {
        categoryId: '02',
        subcategoryId: '1D',
        deviceDescription: 'Commercial Switch with relay',
        modelNumber: '4101',
      },
      '1E': {
        categoryId: '02',
        subcategoryId: '1E',
        productKey: '000000',
        deviceDescription: 'KeypadLinc On/Off (Dual-Band)',
        modelNumber: '2487S',
      },
      '1F': {
        categoryId: '02',
        subcategoryId: '1F',
        productKey: '000000',
        deviceDescription: 'In-LineLinc On/Off (Dual-Band)',
        modelNumber: '2475SDB',
      },
      '20': {
        categoryId: '02',
        subcategoryId: '20',
        productKey: '00008A',
        deviceDescription: 'Wall Keypad Switch',
        modelNumber: '4704',
      },
      '21': {
        categoryId: '02',
        subcategoryId: '21',
        productKey: '00008C',
        deviceDescription: 'Outlet Switch',
        modelNumber: '4707',
      },
      '22': {
        categoryId: '02',
        subcategoryId: '22',
        productKey: '000093',
        deviceDescription: 'In-Line Switch',
        modelNumber: '4713',
      },
      '23': {
        categoryId: '02',
        subcategoryId: '23',
        productKey: '000088',
        deviceDescription: 'Wall Switch',
        modelNumber: '4702',
      },
      '24': {
        categoryId: '02',
        subcategoryId: '24',
        productKey: '0000A1',
        deviceDescription: 'Wall Keypad Switch 277V',
        modelNumber: '4102',
      },
      '25': {
        categoryId: '02',
        subcategoryId: '25',
        productKey: '000000',
        deviceDescription: 'KeypadLinc 8-Button Countdown On/Off Switch Timer',
        modelNumber: '2484SWH8',
      },
      '26': {
        categoryId: '02',
        subcategoryId: '26',
        productKey: '000000',
        deviceDescription: 'Keypad Schedule Timer with On/Off Switch',
        modelNumber: '2485SWH6',
      },
      '29': {
        categoryId: '02',
        subcategoryId: '29',
        productKey: '000000',
        deviceDescription: 'SwitchLinc Relay Countdown Timer',
        modelNumber: '2476ST',
      },
      '2A': {
        categoryId: '02',
        subcategoryId: '2A',
        productKey: '000000',
        deviceDescription: 'SwitchLinc Relay (Dual-Band)',
        modelNumber: '2477S',
      },
      '2B': {
        categoryId: '02',
        subcategoryId: '2B',
        productKey: '000000',
        deviceDescription: 'In-LineLinc On/Off (Dual Band, 50/60 Hz)',
        modelNumber: '2475SDB-50',
      },
      '2C': {
        categoryId: '02',
        subcategoryId: '2C',
        productKey: '000000',
        deviceDescription: 'KeypadLinc On/Off (Dual-Band, 50/60 Hz)',
        modelNumber: '2487S',
      },
      '2D': {
        categoryId: '02',
        subcategoryId: '2D',
        productKey: '000000',
        deviceDescription: 'Insteon On/Off Module, France (869 MHz)',
        modelNumber: '2633-422',
      },
      '2E': {
        categoryId: '02',
        subcategoryId: '2E',
        productKey: '000000',
        deviceDescription: 'Insteon DIN Rail On/Off (915 MHz)',
        modelNumber: '2453-222',
      },
      '2F': {
        categoryId: '02',
        subcategoryId: '2F',
        productKey: '000000',
        deviceDescription: 'Insteon Micro On/Off (915 MHz)',
        modelNumber: '2443-222',
      },
      '30': {
        categoryId: '02',
        subcategoryId: '30',
        productKey: '000000',
        deviceDescription: 'Insteon On/Off Module, Germany (869 MHz)',
        modelNumber: '2633-432',
      },
      '31': {
        categoryId: '02',
        subcategoryId: '31',
        productKey: '000000',
        deviceDescription: 'Insteon Micro On/Off (869 MHz)',
        modelNumber: '2443-422',
      },
      '32': {
        categoryId: '02',
        subcategoryId: '32',
        productKey: '000000',
        deviceDescription: 'Insteon Micro On/Off (921 MHz)',
        modelNumber: '2443-522',
      },
      '33': {
        categoryId: '02',
        subcategoryId: '33',
        productKey: '000000',
        deviceDescription: 'Insteon DIN Rail On/Off (869 MHz)',
        modelNumber: '2453-422',
      },
      '34': {
        categoryId: '02',
        subcategoryId: '34',
        productKey: '000000',
        deviceDescription: 'Insteon DIN Rail On/Off (921 MHz)',
        modelNumber: '2453-522',
      },
      '35': {
        categoryId: '02',
        subcategoryId: '35',
        productKey: '000000',
        deviceDescription: 'Insteon On/Off Module, UK (869 MHz)',
        modelNumber: '2633-442',
      },
      '36': {
        categoryId: '02',
        subcategoryId: '36',
        productKey: '000000',
        deviceDescription: 'Insteon On/Off Module, Aus/NZ (921 MHz)',
        modelNumber: '2633-522',
      },
      '37': {
        categoryId: '02',
        subcategoryId: '37',
        productKey: '000000',
        deviceDescription: 'Insteon On/Off Module, US (915 MHz)',
        modelNumber: '2635-222',
      },
      '38': {
        categoryId: '02',
        subcategoryId: '38',
        productKey: '000000',
        deviceDescription: 'On/Off Outdoor Module (Dual-Band)',
        modelNumber: '2634-222',
      },
      '39': {
        categoryId: '02',
        subcategoryId: '39',
        productKey: '000000',
        deviceDescription: 'On/Off Outlet',
        modelNumber: '2663-222',
      },
      '3A': {
        categoryId: '02',
        subcategoryId: '3A',
        deviceDescription: 'Insteon On/Off Module, Chile (915 MHz)',
        modelNumber: '2633-452',
      },
    },
  },
  '03': {
    categoryId: '03',
    categoryName: 'Network Bridges',
    examplesOfDevices: 'PowerLinc Controllers, TRex, Lonworks, ZigBee, etc.',
    subcategories: {
      '01': {
        categoryId: '03',
        subcategoryId: '01',
        productKey: '000000',
        deviceDescription: 'PowerLinc Serial Controller',
        modelNumber: '2414S',
      },
      '02': {
        categoryId: '03',
        subcategoryId: '02',
        productKey: '000000',
        deviceDescription: 'PowerLinc USB Controller',
        modelNumber: '2414U',
      },
      '03': {
        categoryId: '03',
        subcategoryId: '03',
        productKey: '000000',
        deviceDescription: 'ICON PowerLinc Serial',
        modelNumber: '2814S',
      },
      '04': {
        categoryId: '03',
        subcategoryId: '04',
        productKey: '000000',
        deviceDescription: 'ICON PowerLinc USB',
        modelNumber: '2814U',
      },
      '05': {
        categoryId: '03',
        subcategoryId: '05',
        productKey: '00000C',
        deviceDescription: 'PowerLinc Serial Modem',
        modelNumber: '2412S',
      },
      '06': {
        categoryId: '03',
        subcategoryId: '06',
        productKey: '000016',
        deviceDescription: 'IRLinc Receiver',
        modelNumber: '2411R',
      },
      '07': {
        categoryId: '03',
        subcategoryId: '07',
        productKey: '000017',
        deviceDescription: 'IRLinc Transmitter',
        modelNumber: '2411T',
      },
      '08': {
        categoryId: '03',
        subcategoryId: '08',
        productKey: '000018',
        deviceDescription: 'SmartLabs Bi-Directional IR -Insteon Interface',
      },
      '09': {
        categoryId: '03',
        subcategoryId: '09',
        productKey: '000019',
        deviceDescription: 'SmartLabs RF Developer\'s Board',
        modelNumber: '2600RF',
      },
      '0A': {
        categoryId: '03',
        subcategoryId: '0A',
        productKey: '00000D',
        deviceDescription: 'SeriaLinc - Insteon to RS232',
        modelNumber: '2410S',
      },
      '0B': {
        categoryId: '03',
        subcategoryId: '0B',
        productKey: '000030',
        deviceDescription: 'PowerLinc USB Modem',
        modelNumber: '2412U',
      },
      '0C': {
        categoryId: '03',
        subcategoryId: '0C',
        productKey: '000031',
        deviceDescription: 'SmartLabs PLM Alert Serial',
      },
      '0D': {
        categoryId: '03',
        subcategoryId: '0D',
        productKey: '000035',
        deviceDescription: 'SimpleHomeNet EZX10RF',
      },
      '0E': {
        categoryId: '03',
        subcategoryId: '0E',
        productKey: '00002C',
        deviceDescription: 'X10 TW-523/PSC05 Translator',
      },
      '0F': {
        categoryId: '03',
        subcategoryId: '0F',
        productKey: '00003B',
        deviceDescription: 'EZX10IR X10 IR Receiver',
        modelNumber: 'EZX10IR',
      },
      '10': {
        categoryId: '03',
        subcategoryId: '10',
        productKey: '000044',
        deviceDescription: 'SmartLinc',
        modelNumber: '2412N',
      },
      '11': {
        categoryId: '03',
        subcategoryId: '11',
        productKey: '000045',
        deviceDescription: 'PowerLinc Serial Modem (Dual Band)',
        modelNumber: '2413S',
      },
      '12': {
        categoryId: '03',
        subcategoryId: '12',
        productKey: '00004C',
        deviceDescription: 'RF Modem Card',
        modelNumber: '',
      },
      '13': {
        categoryId: '03',
        subcategoryId: '13',
        productKey: '000030',
        deviceDescription: 'PowerLinc USB Modem for HouseLinc',
        modelNumber: '2412UH',
      },
      '14': {
        categoryId: '03',
        subcategoryId: '14',
        productKey: '00000C',
        deviceDescription: 'PowerLinc Serial Modem for HouseLinc',
        modelNumber: '2412SH',
      },
      '15': {
        categoryId: '03',
        subcategoryId: '15',
        productKey: '000000',
        deviceDescription: 'PowerLinc USB Modem (Dual Band)',
        modelNumber: '2413U',
      },
      '18': {
        categoryId: '03',
        subcategoryId: '18',
        productKey: '000000',
        deviceDescription: 'Insteon Central Controller (915 MHz)',
        modelNumber: '2243-222',
      },
      '19': {
        categoryId: '03',
        subcategoryId: '19',
        productKey: '000000',
        deviceDescription: 'PowerLinc Serial Modem for HouseLinc (Dual Band)',
        modelNumber: '2413SH',
      },
      '1A': {
        categoryId: '03',
        subcategoryId: '1A',
        productKey: '000000',
        deviceDescription: 'PowerLinc USB Modem for HouseLinc (Dual Band)',
        modelNumber: '2413UH',
      },
      '1B': {
        categoryId: '03',
        subcategoryId: '1B',
        productKey: '000000',
        deviceDescription: 'iGateway',
        modelNumber: '2423A4',
      },
      '1C': {
        categoryId: '03',
        subcategoryId: '1C',
        deviceDescription: 'iGateway 2.0',
        modelNumber: '2423A7',
      },
      '1E': {
        categoryId: '03',
        subcategoryId: '1E',
        deviceDescription: 'PowerLinc Serial Modem w/o EEPROM (w/o RF)',
        modelNumber: '2412S',
      },
      '1F': {
        categoryId: '03',
        subcategoryId: '1F',
        productKey: '00007E',
        deviceDescription: 'USB Adapter - Domestically made',
        modelNumber: '2448A7',
      },
      '20': {
        categoryId: '03',
        subcategoryId: '20',
        productKey: '00007E',
        deviceDescription: 'USB Adapter',
        modelNumber: '2448A7',
      },
      '21': {
        categoryId: '03',
        subcategoryId: '21',
        productKey: '00008E',
        deviceDescription: 'Portable USB Adapter for HouseLinc',
        modelNumber: '2448A7H',
      },
      '22': {
        categoryId: '03',
        subcategoryId: '22',
        productKey: '00008F',
        deviceDescription: 'Central Controller Interface',
        modelNumber: '4706A',
      },
      '23': {
        categoryId: '03',
        subcategoryId: '23',
        productKey: '00008E',
        deviceDescription: 'Portable USB Adapter for HouseLinc',
        modelNumber: '2448A7H',
      },
      '24': {
        categoryId: '03',
        subcategoryId: '24',
        productKey: '0000A2',
        deviceDescription: 'TouchLinc',
        modelNumber: '2448A7T',
      },
      '27': {
        categoryId: '03',
        subcategoryId: '27',
        productKey: '0000A2',
        deviceDescription: 'TouchLinc',
        modelNumber: '2448A7T',
      },
      '28': {
        categoryId: '03',
        subcategoryId: '28',
        deviceDescription: 'Global PLM, Dual Band (915 MHz)',
        modelNumber: '2413Gxx',
      },
      '29': {
        categoryId: '03',
        subcategoryId: '29',
        deviceDescription: 'PowerLinc Serial Modem (Dual Band) RF OFF, Auto Detect 128K',
        modelNumber: '2413SAD',
      },
      '2B': {
        categoryId: '03',
        subcategoryId: '2B',
        productKey: '000000',
        deviceDescription: 'Insteon Hub (915 MHz) - no RF',
        modelNumber: '2242-222',
      },
      '2C': {
        categoryId: '03',
        subcategoryId: '2C',
        productKey: '000000',
        deviceDescription: 'Central Controller',
        modelNumber: '2243-442',
      },
      '2D': {
        categoryId: '03',
        subcategoryId: '2D',
        productKey: '000000',
        deviceDescription: 'Central Controller',
        modelNumber: '2243-522',
      },
      '2E': {
        categoryId: '03',
        subcategoryId: '2E',
        productKey: '000000',
        deviceDescription: 'Insteon Hub (EU - 869 MHz)',
        modelNumber: '2242-422',
      },
      '2F': {
        categoryId: '03',
        subcategoryId: '2F',
        productKey: '000000',
        deviceDescription: 'Insteon Hub (921 MHz)',
        modelNumber: '2242-522',
      },
      '30': {
        categoryId: '03',
        subcategoryId: '30',
        productKey: '000000',
        deviceDescription: 'Insteon Hub (UK - 869 MHz)',
        modelNumber: '2242-442',
      },
      '31': {
        categoryId: '03',
        subcategoryId: '31',
        productKey: '000000',
        deviceDescription: 'Insteon Hub (Plug-In Version)',
        modelNumber: '2242-232',
      },
      '32': {
        categoryId: '03',
        subcategoryId: '32',
        productKey: '000000',
        deviceDescription: 'Hub',
        modelNumber: '2242-222',
      },
      '33': {
        categoryId: '03',
        subcategoryId: '33',
        productKey: '000000',
        deviceDescription: 'Insteon Hub II (915 MHz)',
        modelNumber: '2245-222',
      },
      '34': {
        categoryId: '03',
        subcategoryId: '34',
        productKey: '000000',
        deviceDescription: 'Hub',
        modelNumber: '2245-442',
      },
      '35': {
        categoryId: '03',
        subcategoryId: '35',
        productKey: '000000',
        deviceDescription: 'Hub',
        modelNumber: '2245-422',
      },
      '36': {
        categoryId: '03',
        subcategoryId: '36',
        productKey: '000000',
        deviceDescription: 'Hub',
        modelNumber: '2245-522',
      },
      '37': {
        categoryId: '03',
        subcategoryId: '37',
        productKey: '000000',
        deviceDescription: 'Insteon Hub (915 MHz) - RF',
        modelNumber: '2242-222',
      },
    },
  },
  '04': {
    categoryId: '04',
    categoryName: 'Irrigation Control',
    examplesOfDevices: 'Irrigation Management, Sprinkler Controllers',
    subcategories: {
      '00': {
        categoryId: '04',
        subcategoryId: '00',
        productKey: '000001',
        deviceDescription: 'Compacta EZRain Sprinkler Controller',
        modelNumber: '31270',
      },
    },
  },
  '05': {
    categoryId: '05',
    categoryName: 'Climate Control',
    examplesOfDevices: 'Heating, Air conditioning, Exhausts Fans, Ceiling Fans, Indoor Air Quality',
    subcategories: {
      '00': {
        categoryId: '05',
        subcategoryId: '00',
        productKey: '000000',
        deviceDescription: 'Broan SMSC080 Exhaust Fan (no beeper)',
        modelNumber: '2670IAQ-80',
      },
      '01': {
        categoryId: '05',
        subcategoryId: '01',
        productKey: '000002',
        deviceDescription: 'EZTherm',
      },
      '02': {
        categoryId: '05',
        subcategoryId: '02',
        productKey: '000000',
        deviceDescription: 'Broan SMSC110 Exhaust Fan (no beeper)',
        modelNumber: '2670IAQ-110',
      },
      '03': {
        categoryId: '05',
        subcategoryId: '03',
        productKey: '00001F',
        deviceDescription: 'Thermostat Adapter',
        modelNumber: '2441V',
      },
      '04': {
        categoryId: '05',
        subcategoryId: '04',
        productKey: '000024',
        deviceDescription: 'EZThermx',
      },
      '05': {
        categoryId: '05',
        subcategoryId: '05',
        productKey: '000038',
        deviceDescription: 'Broan, Venmar, BEST Rangehoods',
      },
      '06': {
        categoryId: '05',
        subcategoryId: '06',
        productKey: '000043',
        deviceDescription: 'Broan SmartSense Make-up Damper',
      },
      '07': {
        categoryId: '05',
        subcategoryId: '07',
        productKey: '000000',
        deviceDescription: 'Insteon Wireless Thermostat',
        modelNumber: '2441ZT',
      },
      '08': {
        categoryId: '05',
        subcategoryId: '08',
        productKey: '000000',
        deviceDescription: 'Thermostat',
        modelNumber: '2441TH',
      },
      '09': {
        categoryId: '05',
        subcategoryId: '09',
        productKey: '000094',
        deviceDescription: '7 Day Thermostat',
        modelNumber: '4715',
      },
      '0A': {
        categoryId: '05',
        subcategoryId: '0A',
        productKey: '000000',
        deviceDescription: 'Insteon Wireless Thermostat (915 MHz)',
        modelNumber: '2441ZTH',
      },
      '0B': {
        categoryId: '05',
        subcategoryId: '0B',
        productKey: '000000',
        deviceDescription: 'Insteon Thermostat (915 MHz)',
        modelNumber: '2441TH',
      },
      '0C': {
        categoryId: '05',
        subcategoryId: '0C',
        deviceDescription: 'Broan SMSC080 Switch for 80CFM Fans',
        modelNumber: '2670IAQ-80',
      },
      '0D': {
        categoryId: '05',
        subcategoryId: '0D',
        productKey: '000000',
        deviceDescription: 'Broan SMSC110 Switch for 110CFM Fans',
        modelNumber: '2670IAQ-110',
      },
      '0E': {
        categoryId: '05',
        subcategoryId: '0E',
        productKey: '000000',
        deviceDescription: 'Integrated Remote Control Thermostat',
        modelNumber: '2491T1E',
      },
      '0F': {
        categoryId: '05',
        subcategoryId: '0F',
        productKey: '000000',
        deviceDescription: 'Insteon Thermostat (869 MHz)',
        modelNumber: '2732-422',
      },
      '10': {
        categoryId: '05',
        subcategoryId: '10',
        productKey: '000000',
        deviceDescription: 'Insteon Thermostat (921 MHz)',
        modelNumber: '2732-522',
      },
      '11': {
        categoryId: '05',
        subcategoryId: '11',
        productKey: '000000',
        deviceDescription: 'Insteon Zone Thermostat (869 MHz)',
        modelNumber: '2732-432',
      },
      '12': {
        categoryId: '05',
        subcategoryId: '12',
        productKey: '000000',
        deviceDescription: 'Insteon Zone Thermostat (921 MHz)',
        modelNumber: '2732-532',
      },
      '13': {
        categoryId: '05',
        subcategoryId: '13',
        deviceDescription: 'Heat Pump Thermostat - US/Can (915MHz)',
        modelNumber: '2732-242',
      },
      '14': {
        categoryId: '05',
        subcategoryId: '14',
        deviceDescription: 'Heat Pump Thermostat - Europe (869.85MHz)',
        modelNumber: '2732-242',
      },
      '15': {
        categoryId: '05',
        subcategoryId: '15',
        deviceDescription: 'Heat Pump Thermostat - Aus/NZ (921MHz)',
        modelNumber: '2732-242',
      },
    },
  },
  '06': {
    categoryId: '06',
    categoryName: 'Pool and Spa Control',
    examplesOfDevices: 'Pumps, Heaters, Chemicals',
    subcategories: {
      '00': {
        categoryId: '06',
        subcategoryId: '00',
        productKey: '000003',
        deviceDescription: 'EZPool',
      },
      '01': {
        categoryId: '06',
        subcategoryId: '01',
        productKey: '000008',
        deviceDescription: 'Low-end pool controller (Temp. Eng. Project name)',
      },
      '02': {
        categoryId: '06',
        subcategoryId: '02',
        productKey: '000009',
        deviceDescription: 'Mid-Range pool controller (Temp. Eng. Project name)',
      },
      '03': {
        categoryId: '06',
        subcategoryId: '03',
        productKey: '00000A',
        deviceDescription: 'Next Generation pool controller (Temp. Eng. Project name)',
      },
    },
  },
  '07': {
    categoryId: '07',
    categoryName: 'Sensors and Actuators',
    examplesOfDevices: 'Sensors, Contact Closures',
    subcategories: {
      '00': {
        categoryId: '07',
        subcategoryId: '00',
        productKey: '00001A',
        deviceDescription: 'I/O Linc',
        modelNumber: '2450',
      },
      '01': {
        categoryId: '07',
        subcategoryId: '01',
        productKey: '000004',
        deviceDescription: 'EZSns1W Sensor Interface Module',
      },
      '02': {
        categoryId: '07',
        subcategoryId: '02',
        productKey: '000012',
        deviceDescription: 'EZIO8T I/O Module',
      },
      '03': {
        categoryId: '07',
        subcategoryId: '03',
        productKey: '000005',
        deviceDescription: 'Compacta EZIO2X4 #5010D',
        modelNumber: '31274',
      },
      '04': {
        categoryId: '07',
        subcategoryId: '04',
        productKey: '000013',
        deviceDescription: 'EZIO8SA',
      },
      '05': {
        categoryId: '07',
        subcategoryId: '05',
        productKey: '000014',
        deviceDescription: 'Compacta EZSnsRF RcvrIntrfc Dakota Alert',
        modelNumber: '31275',
      },
      '06': {
        categoryId: '07',
        subcategoryId: '06',
        productKey: '000015',
        deviceDescription: 'EZISnsRf',
      },
      '07': {
        categoryId: '07',
        subcategoryId: '07',
        productKey: '000014',
        deviceDescription: 'EZIO6I (6 inputs)',
        modelNumber: '31280',
      },
      '08': {
        categoryId: '07',
        subcategoryId: '08',
        productKey: '000014',
        deviceDescription: 'EZIO4O (4 relay outputs)',
        modelNumber: '31283',
      },
      '09': {
        categoryId: '07',
        subcategoryId: '09',
        productKey: '000000',
        deviceDescription: 'SynchroLinc',
        modelNumber: '2423A5',
      },
      '0C': {
        categoryId: '07',
        subcategoryId: '0C',
        deviceDescription: 'Lumistat',
        modelNumber: '2448A5',
      },
      '0D': {
        categoryId: '07',
        subcategoryId: '0D',
        productKey: '000000',
        deviceDescription: 'I/O Linc 50/60Hz Auto Detect',
        modelNumber: '2450',
      },
      '0E': {
        categoryId: '07',
        subcategoryId: '0E',
        productKey: '000000',
        deviceDescription: 'I/O Module - US (915 MHz)',
        modelNumber: '2248-222',
      },
      '0F': {
        categoryId: '07',
        subcategoryId: '0F',
        productKey: '000000',
        deviceDescription: 'I/O Module - EU (869.85 MHz)',
        modelNumber: '2248-422',
      },
      '10': {
        categoryId: '07',
        subcategoryId: '10',
        productKey: '000000',
        deviceDescription: 'I/O Module - UK (869.85 MHz)',
        modelNumber: '2248-442',
      },
      '11': {
        categoryId: '07',
        subcategoryId: '11',
        productKey: '000000',
        deviceDescription: 'I/O Module - AUS (921 MHz)',
        modelNumber: '2248-522',
      },
      '12': {
        categoryId: '07',
        subcategoryId: '12',
        deviceDescription: 'IOLinc Dual-Band - US',
        modelNumber: '2822-222',
      },
      '13': {
        categoryId: '07',
        subcategoryId: '13',
        deviceDescription: 'IOLinc Dual-Band - EU',
        modelNumber: '2822-422',
      },
      '14': {
        categoryId: '07',
        subcategoryId: '14',
        deviceDescription: 'IOLinc Dual-Band - UK',
        modelNumber: '2822-442',
      },
      '15': {
        categoryId: '07',
        subcategoryId: '15',
        deviceDescription: 'IOLinc Dual-Band - AUS/NZ',
        modelNumber: '2822-522',
      },
      '16': {
        categoryId: '07',
        subcategoryId: '16',
        deviceDescription: 'Low Voltage/Contact Closure Interface (Dual Band) - US',
        modelNumber: '2822-222',
      },
      '17': {
        categoryId: '07',
        subcategoryId: '17',
        deviceDescription: 'Low Voltage/Contact Closure Interface (Dual Band) - EU',
        modelNumber: '2822-422',
      },
      '18': {
        categoryId: '07',
        subcategoryId: '18',
        deviceDescription: 'Low Voltage/Contact Closure Interface (Dual Band) - UK',
        modelNumber: '2822-442',
      },
      '19': {
        categoryId: '07',
        subcategoryId: '19',
        deviceDescription: 'Low Voltage/Contact Closure Interface (Dual Band) - AUS/NZ',
        modelNumber: '2822-522',
      },
      '1E': {
        categoryId: '07',
        subcategoryId: '1E',
        productKey: '000000',
        deviceDescription: 'INSTEON Siren',
        modelNumber: '2868-222',
      },
    },
  },
  '08': {
    categoryId: '08',
    categoryName: 'Home Entertainment',
    examplesOfDevices: 'Audio/Video Equipment',
    subcategories: {},
  },
  '09': {
    categoryId: '09',
    categoryName: 'Energy Management',
    examplesOfDevices: 'Electricity, Water, Gas Consumption, Leak Monitors',
    subcategories: {
      '00': {
        categoryId: '09',
        subcategoryId: '00',
        productKey: '000006',
        deviceDescription: 'EZEnergy',
      },
      '01': {
        categoryId: '09',
        subcategoryId: '01',
        productKey: '000020',
        deviceDescription: 'OnSitePro Leak Detector',
      },
      '02': {
        categoryId: '09',
        subcategoryId: '02',
        productKey: '000021',
        deviceDescription: 'OnSitePro Control Valve',
      },
      '03': {
        categoryId: '09',
        subcategoryId: '03',
        productKey: '000025',
        deviceDescription: 'Energy Inc. TED 5000 Single Phase Measuring Transmitting Unit (MTU)',
      },
      '04': {
        categoryId: '09',
        subcategoryId: '04',
        productKey: '000026',
        deviceDescription: 'Energy Inc. TED 5000 Gateway - USB',
      },
      '05': {
        categoryId: '09',
        subcategoryId: '05',
        productKey: '00002A',
        deviceDescription: 'Energy Inc. TED 5000 Gateway - Ethernet',
      },
      '06': {
        categoryId: '09',
        subcategoryId: '06',
        productKey: '00002B',
        deviceDescription: 'Energy Inc. TED 3000 Three Phase Measuring Transmitting Unit (MTU)',
      },
      '07': {
        categoryId: '09',
        subcategoryId: '07',
        productKey: '000000',
        deviceDescription: 'iMeter Solo',
        modelNumber: '2423A1',
      },
      '08': {
        categoryId: '09',
        subcategoryId: '08',
        deviceDescription: 'iMeter Home (Breaker Panel)',
        modelNumber: '2423A2',
      },
      '09': {
        categoryId: '09',
        subcategoryId: '09',
        deviceDescription: 'iMeter Home (Meter)',
        modelNumber: '2423A3',
      },
      '0A': {
        categoryId: '09',
        subcategoryId: '0A',
        productKey: '000000',
        deviceDescription: '220/240V 30A Load Controller NO (DB)',
        modelNumber: '2477SA1',
      },
      '0B': {
        categoryId: '09',
        subcategoryId: '0B',
        productKey: '000000',
        deviceDescription: '220/240V 30A Load Controller NC (DB)',
        modelNumber: '2477SA2',
      },
      '0C': {
        categoryId: '09',
        subcategoryId: '0C',
        deviceDescription: 'GE Water Heater U-SNAP module',
        modelNumber: '2630A1',
      },
      '0D': {
        categoryId: '09',
        subcategoryId: '0D',
        deviceDescription: 'Energy Display',
        modelNumber: '2448A2',
      },
      '0E': {
        categoryId: '09',
        subcategoryId: '0E',
        deviceDescription: 'Power Strip with iMeter and SynchroLinc',
        modelNumber: '2423A6',
      },
      '10': {
        categoryId: '09',
        subcategoryId: '10',
        productKey: '000090',
        deviceDescription: 'Network Hub',
        modelNumber: '4700',
      },
      '11': {
        categoryId: '09',
        subcategoryId: '11',
        deviceDescription: 'Insteon Digital Meter Reader',
        modelNumber: '2423A8',
      },
    },
  },
  '0A': {
    categoryId: '0A',
    categoryName: 'Built-In Appliance Control',
    examplesOfDevices: 'White Goods, Brown Goods',
    subcategories: {},
  },
  '0B': {
    categoryId: '0B',
    categoryName: 'Plumbing',
    examplesOfDevices: 'Faucets, Showers, Toilets',
    subcategories: {},
  },
  '0C': {
    categoryId: '0C',
    categoryName: 'Communication',
    examplesOfDevices: 'Telephone System Controls, Intercoms',
    subcategories: {},
  },
  '0D': {
    categoryId: '0D',
    categoryName: 'Computer Control',
    examplesOfDevices: 'PC On/Off, UPS Control, App Activation, Remote Mouse, Keyboards',
    subcategories: {},
  },
  '0E': {
    categoryId: '0E',
    categoryName: 'Window Coverings',
    examplesOfDevices: 'Drapes, Blinds, Awnings',
    subcategories: {
      '00': {
        categoryId: '0E',
        subcategoryId: '00',
        productKey: '00000B',
        deviceDescription: 'Somfy Drape Controller RF Bridge',
        modelNumber: '318276I',
      },
      '01': {
        categoryId: '0E',
        subcategoryId: '01',
        productKey: '000000',
        deviceDescription: 'Insteon Micro Open/Close (915 MHz)',
        modelNumber: '2444-222',
      },
      '02': {
        categoryId: '0E',
        subcategoryId: '02',
        productKey: '000000',
        deviceDescription: 'Insteon Micro Open/Close (869 MHz)',
        modelNumber: '2444-422',
      },
      '03': {
        categoryId: '0E',
        subcategoryId: '03',
        productKey: '000000',
        deviceDescription: 'Insteon Micro Open/Close (921 MHz)',
        modelNumber: '2444-522',
      },
      '04': {
        categoryId: '0E',
        subcategoryId: '04',
        deviceDescription: 'Window Shade Kit - US',
        modelNumber: '2772-222',
      },
      '05': {
        categoryId: '0E',
        subcategoryId: '05',
        deviceDescription: 'Window Shade Kit - EU',
        modelNumber: '2772-422',
      },
      '06': {
        categoryId: '0E',
        subcategoryId: '06',
        deviceDescription: 'Window Shade Kit - AUS/NZ',
        modelNumber: '2772-522',
      },
    },
  },
  '0F': {
    categoryId: '0F',
    categoryName: 'Access Control',
    examplesOfDevices: 'Automatic Doors, Gates, Windows, Locks',
    subcategories: {
      '00': {
        categoryId: '0F',
        subcategoryId: '00',
        productKey: '00000E',
        deviceDescription: 'Weiland Doors\' Central Drive and Controller',
      },
      '01': {
        categoryId: '0F',
        subcategoryId: '01',
        productKey: '00000F',
        deviceDescription: 'Weiland Doors\' Secondary Central Drive',
      },
      '02': {
        categoryId: '0F',
        subcategoryId: '02',
        productKey: '000010',
        deviceDescription: 'Weiland Doors\' Assist Drive',
      },
      '03': {
        categoryId: '0F',
        subcategoryId: '03',
        productKey: '000011',
        deviceDescription: 'Weiland Doors\' Elevation Drive',
      },
      '04': {
        categoryId: '0F',
        subcategoryId: '04',
        productKey: '000000',
        deviceDescription: 'GarageHawk Garage Unit',
      },
      '05': {
        categoryId: '0F',
        subcategoryId: '05',
        productKey: '000000',
        deviceDescription: 'GarageHawk Remote Unit',
      },
      '06': {
        categoryId: '0F',
        subcategoryId: '06',
        productKey: '000000',
        deviceDescription: 'MorningLinc',
        modelNumber: '2458A1',
      },
      '0A': {
        categoryId: '0F',
        subcategoryId: '0A',
        productKey: '000000',
        deviceDescription: 'Lock Controller',
        modelNumber: '2862-222',
      },
    },
  },
  '10': {
    categoryId: '10',
    categoryName: 'Security, Health, Safety',
    examplesOfDevices: 'Door and Window Sensors, Motion Sensors, Scales',
    subcategories: {
      '00': {
        categoryId: '10',
        subcategoryId: '00',
        productKey: '000027',
        deviceDescription: 'First Alert ONELink RF to Insteon Bridge',
      },
      '01': {
        categoryId: '10',
        subcategoryId: '01',
        productKey: '00004A',
        deviceDescription: 'Motion Sensor - US (915 MHz)',
        modelNumber: '2842-222',
      },
      '02': {
        categoryId: '10',
        subcategoryId: '02',
        productKey: '000049',
        deviceDescription: 'Insteon Open/Close Sensor (915 MHz)',
        modelNumber: '2843-222',
      },
      '03': {
        categoryId: '10',
        subcategoryId: '03',
        productKey: '0000A0',
        deviceDescription: 'Motion Sensor',
        modelNumber: '4716',
      },
      '04': {
        categoryId: '10',
        subcategoryId: '04',
        productKey: '000000',
        deviceDescription: 'Insteon Motion Sensor (869 MHz)',
        modelNumber: '2842-422',
      },
      '05': {
        categoryId: '10',
        subcategoryId: '05',
        productKey: '000000',
        deviceDescription: 'Insteon Motion Sensor (921 MHz)',
        modelNumber: '2842-522',
      },
      '06': {
        categoryId: '10',
        subcategoryId: '06',
        productKey: '000000',
        deviceDescription: 'Insteon Open/Close Sensor (869 MHz)',
        modelNumber: '2843-422',
      },
      '07': {
        categoryId: '10',
        subcategoryId: '07',
        productKey: '000000',
        deviceDescription: 'Insteon Open/Close Sensor (921 MHz)',
        modelNumber: '2843-522',
      },
      '08': {
        categoryId: '10',
        subcategoryId: '08',
        productKey: '000000',
        deviceDescription: 'Leak Sensor - US (915 MHz)',
        modelNumber: '2852-222',
      },
      '09': {
        categoryId: '10',
        subcategoryId: '09',
        productKey: '000000',
        deviceDescription: 'Insteon Door Sensor',
        modelNumber: '2843-232',
      },
      '0A': {
        categoryId: '10',
        subcategoryId: '0A',
        productKey: '000000',
        deviceDescription: 'Smoke Bridge',
        modelNumber: '2982-222',
      },
      '0D': {
        categoryId: '10',
        subcategoryId: '0D',
        deviceDescription: 'Leak Sensor - EU (869 MHz)',
        modelNumber: '2852-422',
      },
      '0E': {
        categoryId: '10',
        subcategoryId: '0E',
        deviceDescription: 'Leak Sensor - AUS/NZ (921 MHz)',
        modelNumber: '2852-522',
      },
      '11': {
        categoryId: '10',
        subcategoryId: '11',
        productKey: '000000',
        deviceDescription: 'Door Sensor II (915 MHz)',
        modelNumber: '2845-222',
      },
      '13': {
        categoryId: '10',
        subcategoryId: '13',
        productKey: '000000',
        deviceDescription: 'Thermostat Heat Pump',
        modelNumber: '2732-232',
      },
      '14': {
        categoryId: '10',
        subcategoryId: '14',
        productKey: '000000',
        deviceDescription: 'Door Sensor II (869 MHz)',
        modelNumber: '2845-422',
      },
      '15': {
        categoryId: '10',
        subcategoryId: '15',
        productKey: '000000',
        deviceDescription: 'Door Sensor II (921 MHz)',
        modelNumber: '2845-522',
      },
      '16': {
        categoryId: '10',
        subcategoryId: '16',
        productKey: '000000',
        deviceDescription: 'Motion Sensor - US (915 MHz)',
        modelNumber: '2844-222',
      },
      '17': {
        categoryId: '10',
        subcategoryId: '17',
        productKey: '000000',
        deviceDescription: 'Thermostat Heat Pump',
        modelNumber: '2732-422',
      },
      '18': {
        categoryId: '10',
        subcategoryId: '18',
        productKey: '000000',
        deviceDescription: 'Thermostat Heat Pump',
        modelNumber: '2732-522',
      },
    },
  },
  '11': {
    categoryId: '11',
    categoryName: 'Surveillance',
    examplesOfDevices: 'Video Camera Control, Time-lapse Recorders, Security System Links',
    subcategories: {},
  },
  '12': {
    categoryId: '12',
    categoryName: 'Automotive',
    examplesOfDevices: 'Remote Starters, Car Alarms, Car Door Locks',
    subcategories: {},
  },
  '13': {
    categoryId: '13',
    categoryName: 'Pet Care',
    examplesOfDevices: 'Pet Feeders, Trackers',
    subcategories: {},
  },
  '14': {
    categoryId: '14',
    categoryName: 'Toys',
    examplesOfDevices: 'Model Trains, Robots',
    subcategories: {},
  },
  '15': {
    categoryId: '15',
    categoryName: 'Timekeeping',
    examplesOfDevices: 'Clocks, Alarms, Timers',
    subcategories: {},
  },
  '16': {
    categoryId: '16',
    categoryName: 'Holiday',
    examplesOfDevices: 'Christmas Lights, Displays',
    subcategories: {},
  },
  '17': {
    categoryId: '17',
    categoryName: 'Reserved',
    subcategories: {},
  },
  FE: {
    categoryId: 'FE',
    subcategories: {},
  },
  FF: {
    categoryId: 'FF',
    categoryName: 'Unassigned',
    examplesOfDevices: 'For devices that will be assigned a DevCat and SubCat by software',
    subcategories: {
      '00': {
        categoryId: 'FF',
        subcategoryId: '00',
        productKey: '000000',
        deviceDescription: 'Unrecognized INSTEON Device',
      },
      '01': {
        categoryId: 'FF',
        subcategoryId: '01',
        productKey: '000000',
        deviceDescription: 'Unrecognized INSTEON Device',
      },
    },
  },
}
