'use strict'
const unroll = require('unroll')
const { parsePlmBuffer } = require('../lib/parsePlmBuffer')

unroll.use(it)

describe('parsePlmBuffer', () => {
  let previousParsedCommand

  describe('modem command Send INSTEON Extended-length Message when not enough bytes received', () => {
    let result, buffer

    beforeEach(() => {
      buffer = '0262010203152E00120156780F08CDEF1234567890AB'
      result = parsePlmBuffer(buffer, previousParsedCommand)
    })

    it('should not return a parsed command', () => {
      expect(result.command).toBeUndefined()
      expect(result.buffer).toEqual(buffer)
    })
  })
  describe('modem commands', () => {
    unroll(
      '#buffer should be parsed as #command',
      testArgs => {
        const result = parsePlmBuffer(testArgs.buffer, previousParsedCommand)
        const command = Object.assign({ received: expect.any(String) }, testArgs.command)

        expect(result.command).toEqual(command)
        expect(result.buffer).toBe('')

        // Check response matcher function
        if (result.command?.responseMatcher) {
          expect(result.command.responseMatcher({ code: '57' })).toBe(true)
        }
      },
      [
        ['buffer', 'command'],
        [
          '025051560E49EA70800156',
          {
            command: 'INSTEON Standard Message Received',
            code: '50',
            length: 18,
            fromAddress: '51560E',
            messageType: 'broadcast',
            allLink: false,
            acknowledgement: false,
            extendedMessage: false,
            hopsLeft: 0,
            maxHops: 0,
            command1: '01',
            command2: '56',
            deviceCategory: '49',
            deviceSubcategory: 'EA',
            firmware: '70',
            insteonCommand: {
              command: 'SET Button Pressed Responder',
              hardwareVersion: '56',
              messageType: 'broadcast',
              fromAddress: '51560E',
              deviceCategory: '49',
              deviceSubcategory: 'EA',
              firmware: '70',
            },
            bytes: '025051560E49EA70800156',
          },
        ],
        [
          '025051560E000070C01100',
          {
            command: 'INSTEON Standard Message Received',
            code: '50',
            length: 18,
            fromAddress: '51560E',
            messageType: 'allLinkBroadcast',
            allLink: true,
            acknowledgement: false,
            extendedMessage: false,
            hopsLeft: 0,
            maxHops: 0,
            command1: '11',
            command2: '00',
            cleanUpCommand1: '00',
            numberDevices: 0,
            groupNumber: 112,
            insteonCommand: {
              command: 'ALL-Link Recall',
              groupNumber: 112,
              command1: '11',
              numberDevices: 0,
              messageType: 'allLinkBroadcast',
              fromAddress: '51560E',
            },
            bytes: '025051560E000070C01100',
          },
        ],
        [
          '0251567890010203152E00120156780F08CDEF1234567890AB',
          {
            command: 'INSTEON Extended Message Received',
            code: '51',
            length: 46,
            messageType: 'direct',
            allLink: false,
            acknowledgement: false,
            extendedMessage: true,
            hopsLeft: 1,
            maxHops: 1,
            fromAddress: '567890',
            toAddress: '010203',
            command1: '2E',
            command2: '00',
            data: '120156780F08CDEF1234567890',
            crc: 'AB',
            insteonCommand: {
              command: 'Extended Set/Get',
              type: 'Data Response',
              groupNumber: 18,
              x10HouseCode: 'J',
              x10UnitCode: 14,
              rampRate: 205,
              onLevel: 239,
              signalToNoiseThreshold: 18,
              ledBrightness: 18,
              fromAddress: '567890',
              toAddress: '010203',
              messageType: 'extendedData',
            },
            bytes: '0251567890010203152E00120156780F08CDEF1234567890AB',
          },
        ],
        [
          '02521200',
          {
            command: 'X10 Received',
            code: '52',
            length: 4,
            x10HouseCode: 'E',
            x10UnitCode: 3,
            bytes: '02521200',
          },
        ],
        [
          '02521280',
          {
            command: 'X10 Received',
            code: '52',
            length: 4,
            x10HouseCode: 'E',
            x10Command: 'On',
            bytes: '02521280',
          },
        ],
        [
          '02530134567890ABCDEF',
          {
            command: 'ALL-Linking Completed',
            code: '53',
            length: 16,
            allLinkType: 'IM is Controller',
            groupNumber: 52,
            deviceAddress: '567890',
            deviceCategory: 'AB',
            deviceSubcategory: 'CD',
            firmwareVersion: 'EF',
            bytes: '02530134567890ABCDEF',
          },
        ],
        [
          '02531234567890ABCDEF', // Unknown All-Link type
          {
            command: 'ALL-Linking Completed',
            code: '53',
            length: 16,
            allLinkType: '12',
            groupNumber: 52,
            deviceAddress: '567890',
            deviceCategory: 'AB',
            deviceSubcategory: 'CD',
            firmwareVersion: 'EF',
            bytes: '02531234567890ABCDEF',
          },
        ],
        [
          '025412',
          {
            command: 'Button Event Report',
            code: '54',
            length: 2,
            buttonNumber: 1,
            buttonEvent: 'Tapped',
            bytes: '025412',
          },
        ],
        [
          '025415', // Unknown button event
          {
            command: 'Button Event Report',
            code: '54',
            length: 2,
            buttonNumber: 1,
            buttonEvent: '5',
            bytes: '025415',
          },
        ],
        [
          '0255',
          {
            command: 'User Reset Detected',
            code: '55',
            length: 0,
            bytes: '0255',
          },
        ],
        [
          '02561234567890',
          {
            command: 'ALL-Link Cleanup Failure Report',
            code: '56',
            length: 10,
            state: '12',
            groupNumber: 52,
            deviceId: '567890',
            bytes: '02561234567890',
          },
        ],
        [
          '0257E2004B2BA6013944',
          {
            command: 'ALL-Link Record Response',
            code: '57',
            length: 16,
            inUse: true,
            isController: true,
            bit5: true,
            bit4: false,
            bit3: false,
            smartHop: 0,
            bit2: false,
            hasBeenUsed: true,
            bit0: false,
            groupNumber: 0,
            id: '4B2BA6',
            deviceCategory: '01',
            deviceSubcategory: '39',
            firmware: '44',
            numberRetries: 1,
            controllerGroupNumber: 68,
            data: '013944',
            bytes: '0257E2004B2BA6013944',
          },
        ],
        [
          '025806',
          {
            command: 'ALL-Link Cleanup Status Report',
            code: '58',
            length: 2,
            ack: true,
            bytes: '025806',
          },
        ],
        [
          '02591FF8E2004B2BA6013944',
          {
            command: 'Database Record Found',
            code: '59',
            length: 20,
            address: '1FF8',
            inUse: true,
            isController: true,
            bit5: true,
            bit4: false,
            bit3: false,
            smartHop: 0,
            bit2: false,
            hasBeenUsed: true,
            bit0: false,
            groupNumber: 0,
            id: '4B2BA6',
            deviceCategory: '01',
            deviceSubcategory: '39',
            firmware: '44',
            numberRetries: 1,
            controllerGroupNumber: 68,
            data: '013944',
            bytes: '02591FF8E2004B2BA6013944',
          },
        ],
        // 5A reserved
        // 5B reserved
        [
          '025C1234567890AB0512EF',
          {
            command: 'INSTEON Message Timed Out',
            code: '5C',
            length: 18,
            address: '1234',
            fromAddress: '123456',
            toAddress: '7890AB',
            command1: '12',
            command2: 'EF',
            messageType: 'direct',
            allLink: false,
            acknowledgement: false,
            extendedMessage: false,
            hopsLeft: 1,
            maxHops: 1,
            insteonCommand: {
              command: 'Light ON Fast',
              onLevel: 239,
              messageType: 'direct',
              fromAddress: '123456',
              toAddress: '7890AB',
            },
            bytes: '025C1234567890AB0512EF',
          },
        ],
        // 5D reserved
        // 5E reserved
        // 5F reserved
        [
          '02601234567890AB06',
          {
            command: 'Get IM Info',
            code: '60',
            length: 14,
            imId: '123456',
            deviceCategory: '78',
            deviceSubcategory: '90',
            firmware: 'AB',
            ack: true,
            bytes: '02601234567890AB06',
          },
        ],
        [
          '026112345606',
          {
            command: 'Send ALL-Link Command',
            code: '61',
            length: 8,
            fromAddress: 'im-hub',
            groupNumber: 18,
            allLinkCommand: '34',
            command2: '56',
            ack: true,
            bytes: '026112345606',
          },
        ],
        [
          '026201020305190006',
          {
            command: 'Send INSTEON Standard-length Message',
            code: '62',
            length: 14,
            messageType: 'direct',
            allLink: false,
            acknowledgement: false,
            extendedMessage: false,
            hopsLeft: 1,
            maxHops: 1,
            fromAddress: 'im-hub',
            toAddress: '010203',
            command1: '19',
            command2: '00',
            ack: true,
            insteonCommand: {
              command: 'Light Status Request',
              messageType: 'direct',
              fromAddress: 'im-hub',
              toAddress: '010203',
            },
            bytes: '026201020305190006',
          },
        ],
        [
          '0262010203152E00120156780F08CDEF1234567890AB06',
          {
            command: 'Send INSTEON Extended-length Message',
            code: '62',
            length: 42,
            messageType: 'direct',
            allLink: false,
            acknowledgement: false,
            extendedMessage: true,
            hopsLeft: 1,
            maxHops: 1,
            fromAddress: 'im-hub',
            toAddress: '010203',
            command1: '2E',
            command2: '00',
            ack: true,
            data: '120156780F08CDEF1234567890',
            crc: 'AB',
            insteonCommand: {
              command: 'Extended Set/Get',
              type: 'Data Response',
              groupNumber: 18,
              x10HouseCode: 'J',
              x10UnitCode: 14,
              rampRate: 205,
              onLevel: 239,
              signalToNoiseThreshold: 18,
              ledBrightness: 18,
              fromAddress: 'im-hub',
              toAddress: '010203',
              messageType: 'extendedData',
            },
            bytes: '0262010203152E00120156780F08CDEF1234567890AB06',
          },
        ],
        [
          '0263123406',
          {
            command: 'Send X10',
            code: '63',
            length: 6,
            x10HouseCode: 'E',
            x10UnitCode: 3,
            ack: true,
            bytes: '0263123406',
          },
        ],
        [
          '0264013406',
          {
            command: 'Start ALL-Linking',
            code: '64',
            length: 6,
            allLinkType: 'IM is Controller',
            groupNumber: 52,
            ack: true,
            bytes: '0264013406',
          },
        ],
        [
          '0264083406',
          {
            command: 'Start ALL-Linking',
            code: '64',
            length: 6,
            allLinkType: '08',
            groupNumber: 52,
            ack: true,
            bytes: '0264083406',
          },
        ],
        [
          '026506',
          {
            command: 'Cancel ALL-Linking',
            code: '65',
            length: 2,
            ack: true,
            bytes: '026506',
          },
        ],
        [
          '026612345606',
          {
            command: 'Set Host Device Category',
            code: '66',
            length: 8,
            deviceCategory: '12',
            deviceSubcategory: '34',
            firmware: '56',
            ack: true,
            bytes: '026612345606',
          },
        ],
        [
          '026706',
          {
            command: 'Reset the IM',
            code: '67',
            length: 2,
            ack: true,
            bytes: '026706',
          },
        ],
        [
          '02681206',
          {
            command: 'Set INSTEON ACK Message Byte',
            code: '68',
            length: 4,
            ack: true,
            command2Data: '12',
            bytes: '02681206',
          },
        ],
        [
          '026906',
          {
            command: 'Get First ALL-Link Record',
            code: '69',
            length: 2,
            ack: true,
            responseMatcher: expect.any(Function),
            bytes: '026906',
          },
        ],
        [
          '026A06',
          {
            command: 'Get Next ALL-Link Record',
            code: '6A',
            length: 2,
            ack: true,
            responseMatcher: expect.any(Function),
            bytes: '026A06',
          },
        ],
        [
          '026B1206',
          {
            command: 'Set IM Configuration',
            code: '6B',
            length: 4,
            ack: true,
            imConfigurationFlags: {
              disableAutomaticLinking: false,
              monitorMode: false,
              disableAutomaticLed: false,
              disableHostComunications: true,
              bit4: false,
              bit3: false,
              bit2: true,
              bit1: false,
            },
            bytes: '026B1206',
          },
        ],
        [
          '026C06',
          {
            command: 'Get ALL-Link Record for Sender',
            code: '6C',
            length: 2,
            ack: true,
            responseMatcher: expect.any(Function),
            bytes: '026C06',
          },
        ],
        [
          '026D06',
          {
            command: 'LED On',
            code: '6D',
            length: 2,
            ack: true,
            bytes: '026D06',
          },
        ],
        [
          '026E06',
          {
            command: 'LED Off',
            code: '6E',
            length: 2,
            ack: true,
            bytes: '026E06',
          },
        ],
        [
          '026F411234567890ABCDEF06',
          {
            command: 'Manage ALL-Link Record',
            code: '6F',
            length: 20,
            controlCode: 'Modify First Responder Found or Add',
            inUse: false,
            isController: false,
            bit5: false,
            bit4: true,
            bit3: false,
            smartHop: 2,
            bit2: false,
            hasBeenUsed: true,
            bit0: false,
            groupNumber: 52,
            id: '567890',
            ack: true,
            bytes: '026F411234567890ABCDEF06',
          },
        ],
        [
          '026F601234567890ABCDEF06',
          {
            command: 'Manage ALL-Link Record',
            code: '6F',
            length: 20,
            controlCode: '60',
            inUse: false,
            isController: false,
            bit5: false,
            bit4: true,
            bit3: false,
            smartHop: 2,
            bit2: false,
            hasBeenUsed: true,
            bit0: false,
            groupNumber: 52,
            id: '567890',
            ack: true,
            bytes: '026F601234567890ABCDEF06',
          },
        ],
        [
          '02703406',
          {
            command: 'Set INSTEON NAK Message Byte',
            code: '70',
            length: 4,
            command2Data: '34',
            ack: true,
            bytes: '02703406',
          },
        ],
        [
          '0271123406',
          {
            command: 'Set INSTEON ACK Message Two Bytes',
            code: '71',
            length: 6,
            command1Data: '12',
            command2Data: '34',
            ack: true,
            bytes: '0271123406',
          },
        ],
        [
          '027206',
          {
            command: 'RF Sleep',
            code: '72',
            length: 2,
            ack: true,
            bytes: '027206',
          },
        ],
        [
          '027312123406',
          {
            command: 'Get IM Configuration',
            code: '73',
            length: 8,
            imConfigurationFlags: {
              disableAutomaticLinking: false,
              monitorMode: false,
              disableAutomaticLed: false,
              disableHostComunications: true,
              bit4: false,
              bit3: false,
              bit2: true,
              bit1: false,
            },
            spare: '1234',
            ack: true,
            bytes: '027312123406',
          },
        ],
        [
          '027406',
          {
            command: 'Cancel Cleanup',
            code: '74',
            length: 2,
            ack: true,
            bytes: '027406',
          },
        ],
        [
          '0275121206',
          {
            command: 'Read 8 bytes from Database',
            code: '75',
            length: 6,
            address: '1212',
            ack: true,
            bytes: '0275121206',
          },
        ],
        [
          '02761234567890123456789006',
          {
            command: 'Write 8 bytes to Database',
            code: '76',
            length: 22,
            address: '1234',
            inUse: false,
            isController: true,
            bit5: false,
            bit4: true,
            bit3: false,
            smartHop: 2,
            bit2: true,
            hasBeenUsed: true,
            bit0: false,
            groupNumber: 120,
            id: '901234',
            ack: true,
            bytes: '02761234567890123456789006',
          },
        ],
        [
          '02771206',
          {
            command: 'Beep',
            code: '77',
            length: 4,
            data: '12',
            ack: true,
            bytes: '02771206',
          },
        ],
        [
          '02781206',
          {
            command: 'Set Status',
            code: '78',
            length: 4,
            status: '12',
            ack: true,
            bytes: '02781206',
          },
        ],
        [
          '027912123406',
          {
            command: 'Set Database Link Data for next Link',
            code: '79',
            length: 8,
            data: '121234',
            ack: true,
            bytes: '027912123406',
          },
        ],
        [
          '027A1206',
          {
            command: 'Set Application Retries for New Links',
            code: '7A',
            length: 4,
            retries: 18,
            ack: true,
            bytes: '027A1206',
          },
        ],
        [
          '027B1206',
          {
            command: 'Set RF Frequency Offset',
            code: '7B',
            length: 4,
            refFrequencyOffset: 18,
            ack: true,
            bytes: '027B1206',
          },
        ],
        [
          '027B8206',
          {
            command: 'Set RF Frequency Offset',
            code: '7B',
            length: 4,
            refFrequencyOffset: -126,
            ack: true,
            bytes: '027B8206',
          },
        ],
        [
          '027C1234567890ABCDEF06',
          {
            command: 'Set Acknowledge for TempLinc command',
            code: '7C',
            length: 18,
            acknowledge: '1234567890ABCDEF',
            ack: true,
            bytes: '027C1234567890ABCDEF06',
          },
        ],
        // 7D reserved
        // 7E reserved
        [
          '027F5106',
          {
            command: 'Unknown Command 7F',
            code: '7F',
            length: 4,
            ack: true,
            data: '51',
            bytes: '027F5106',
          },
        ],
      ]
    )
  })
})
